# Generated by Django 3.0.6 on 2020-05-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=300)),
                ('releaseYear', models.IntegerField()),
                ('moviePoster', models.ImageField(default='movies/posters/defaultPoster.jpg', upload_to='movies/posters')),
                ('movieStill', models.ImageField(default='movies/stills/defaultStill.jpg', upload_to='movies/stills')),
            ],
        ),
        migrations.CreateModel(
            name='Dipen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=300)),
                ('reviewBody', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], default='thumbs_up', max_length=11)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.AllMovies')),
            ],
        ),
        migrations.CreateModel(
            name='Ankur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=300)),
                ('reviewBody', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], default='thumbs_up', max_length=11)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.AllMovies')),
            ],
        ),
    ]
