# Generated by Django 3.0.6 on 2020-05-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allmovies',
            options={'verbose_name_plural': 'All Movies'},
        ),
        migrations.AlterModelOptions(
            name='ankur',
            options={'verbose_name_plural': "Ankur's Reviews"},
        ),
        migrations.AlterModelOptions(
            name='dipen',
            options={'verbose_name_plural': "Dipen's Reviews"},
        ),
        migrations.CreateModel(
            name='Shantnu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=300)),
                ('reviewBody', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], default='thumbs_up', max_length=11)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.AllMovies')),
            ],
            options={
                'verbose_name_plural': "Shantnu's Reviews",
            },
        ),
        migrations.CreateModel(
            name='Jayant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=300)),
                ('reviewBody', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], default='thumbs_up', max_length=11)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.AllMovies')),
            ],
            options={
                'verbose_name_plural': "Jayant's Reviews",
            },
        ),
        migrations.CreateModel(
            name='Ashesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewTitle', models.CharField(max_length=300)),
                ('reviewBody', models.TextField()),
                ('reviewDate', models.DateTimeField()),
                ('verdict', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], default='thumbs_up', max_length=11)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.AllMovies')),
            ],
            options={
                'verbose_name_plural': "Ashesh's Reviews",
            },
        ),
    ]
