# Generated by Django 3.0.6 on 2020-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200529_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmovies',
            name='movieActors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allmovies',
            name='movieAgeRating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allmovies',
            name='movieDirectors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allmovies',
            name='movieGenre',
            field=models.TextField(default='awesome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allmovies',
            name='movieSummary',
            field=models.TextField(default='awesome'),
            preserve_default=False,
        ),
    ]
