# Generated by Django 3.0.6 on 2020-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200607_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingreviews',
            name='moviePoster',
            field=models.ImageField(default='movies/posters/defaultPoster.jpg', upload_to='movies/upcoming'),
        ),
    ]
