# Generated by Django 3.0.6 on 2020-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200607_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmovies',
            old_name='movieGenre',
            new_name='movieGenres',
        ),
        migrations.AddField(
            model_name='allmovies',
            name='movieMoods',
            field=models.TextField(blank=True),
        ),
    ]
