# Generated by Django 3.0.6 on 2020-06-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200614_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingreviews',
            name='movieActors',
        ),
        migrations.RemoveField(
            model_name='upcomingreviews',
            name='movieAgeRating',
        ),
        migrations.RemoveField(
            model_name='upcomingreviews',
            name='movieDirectors',
        ),
        migrations.RemoveField(
            model_name='upcomingreviews',
            name='movieGenre',
        ),
        migrations.RemoveField(
            model_name='upcomingreviews',
            name='movieSummary',
        ),
    ]
